<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseAvalonia>true</UseAvalonia>
    <ImplicitUsings>enable</ImplicitUsings>
  <ApplicationIcon>.\Assets\MermaidStudioIcon_128x128.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Assets\MermaidStudioIcon.png" />
  <SplashScreen Include=".\Assets\SplashScreen.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\MermaidStudioIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MermaidStudio.Domain\MermaidStudio.Domain.csproj" />
    <ProjectReference Include="..\MermaidStudio.Application\MermaidStudio.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Controls\MermaidEditorPaneControl.axaml.cs">
      <DependentUpon>MermaidEditorPaneControl.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
